### ISSUE TITLE
No package 'hidapi-hidraw' found

### ISSUE THREAD

**Issue by blacksocket** [gch1p/isv#2]
Hello,

During compilation I am getting an error below:

pi@raspberrypi:~/isv $ make
gcc -O2 -std=c99 -Wall -W `pkg-config --cflags hidapi-hidraw` -c isv.c -I. -o isv.o
Package hidapi-hidraw was not found in the pkg-config search path.
Perhaps you should add the directory containing `hidapi-hidraw.pc'
to the PKG_CONFIG_PATH environment variable
No package 'hidapi-hidraw' found
gcc -O2 -std=c99 -Wall -W `pkg-config --cflags hidapi-hidraw` -c util.c -I. -o util.o
Package hidapi-hidraw was not found in the pkg-config search path.
Perhaps you should add the directory containing `hidapi-hidraw.pc'
to the PKG_CONFIG_PATH environment variable
No package 'hidapi-hidraw' found
gcc -O2 -std=c99 -Wall -W `pkg-config --cflags hidapi-hidraw` -c p18.c -I. -o p18.o
Package hidapi-hidraw was not found in the pkg-config search path.
Perhaps you should add the directory containing `hidapi-hidraw.pc'
to the PKG_CONFIG_PATH environment variable
No package 'hidapi-hidraw' found
gcc -O2 -std=c99 -Wall -W `pkg-config --cflags hidapi-hidraw` -c print.c -I. -o print.o
Package hidapi-hidraw was not found in the pkg-config search path.
Perhaps you should add the directory containing `hidapi-hidraw.pc'
to the PKG_CONFIG_PATH environment variable
No package 'hidapi-hidraw' found
gcc -O2 -std=c99 -Wall -W `pkg-config --cflags hidapi-hidraw` -c variant.c -I. -o variant.o
Package hidapi-hidraw was not found in the pkg-config search path.
Perhaps you should add the directory containing `hidapi-hidraw.pc'
to the PKG_CONFIG_PATH environment variable
No package 'hidapi-hidraw' found
gcc -O2 -std=c99 -Wall -W `pkg-config --cflags hidapi-hidraw` -c libvoltronic/voltronic_dev_usb_hidapi.c -I. -o libvoltronic/voltronic_dev_usb_hidapi.o
Package hidapi-hidraw was not found in the pkg-config search path.
Perhaps you should add the directory containing `hidapi-hidraw.pc'
to the PKG_CONFIG_PATH environment variable
No package 'hidapi-hidraw' found
libvoltronic/voltronic_dev_usb_hidapi.c:22:10: fatal error: hidapi.h: No such file or directory
 #include "hidapi.h"
          ^~~~~~~~~~
compilation terminated.
make: *** [Makefile:39: libvoltronic/voltronic_dev_usb_hidapi.o] Error 1

However I already installed libhidapi-hidraw0 and libhidapi-libusb0

pi@raspberrypi:/isv $ sudo apt-get install libhidapi-hidraw0
Reading package lists... Done
Building dependency tree
Reading state information... Done
libhidapi-hidraw0 is already the newest version (0.8.0~rc1+git20140818.d17db57+dfsg-2).
0 upgraded, 0 newly installed, 0 to remove and 180 not upgraded.

Could you please help ?

Thank you!

**Comment by gch1p** [comment]
I guess you need to install the dev package:
```
apt install libhidapi-dev
```

Also, please take a look at [inverter-tools](https://github.com/gch1p/inverter-tools), it's a rewrite of isv in c++, it has more features, fewer bugs, and it uses cmake for building.

**Comment by blacksocket** [comment]
Now it works! Thank you very much ;-) Yes I also just compiled the inverter-tools successfully.
